Repository backtrace-labs/backtrace-unity, pull requests merged in 2024-09, with the labels that each got.

#225 Feature/mac support
  Editor/BacktraceClientConfigurationEditor.cs
  Editor/BacktraceConfigurationEditor.cs
  Mac.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/Info.plist
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/MacOS/Backtrace-Unity-Mac-bundle
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/_CodeSignature/CodeResources
  Runtime/BacktraceClient.cs
  Runtime/Model/Attributes/MachineAttributeProvider.cs
  Runtime/Model/BacktraceConfiguration.cs
  Runtime/Native/Base/NativeClientBase.cs
  Runtime/Native/Mac.meta
  Runtime/Native/NativeClientFactory.cs
  Runtime/Native/OSX.meta
  Runtime/Native/OSX/NativeClient.cs
  Runtime/Native/OSX/NativeClient.cs.meta
  Tests/Runtime/Native/BreadcrumbsAnrTests.cs
  Tests/Runtime/Native/Mocks/TestableNativeClient.cs
Labels: enhancement

#227 Add missing bundle and missing configuration
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/Info.plist.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/MacOS.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/MacOS/Backtrace-Unity-Mac-bundle.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/_CodeSignature.meta
  Mac/Backtrace-Unity-Mac-bundle.bundle/Contents/_CodeSignature/CodeResources.meta
  Runtime/Model/BacktraceConfiguration.cs
Labels: bug

#226 Internet availability checks
  Runtime/BacktraceDatabase.cs
  Runtime/Model/Breadcrumbs/BacktraceBreadcrumbs.cs
  Runtime/Model/Breadcrumbs/BacktraceBreadcrumbsEventHandler.cs
  Runtime/Model/Breadcrumbs/IBacktraceBreadcrumbs.cs
Labels: bug

#229 Release 3.10.0
  CHANGELOG.md
  Runtime/BacktraceClient.cs
  Runtime/Native/Mac.meta
  package.json
Labels: release
